version: '3'
services:
        jenkins:
           build: .
           ports:
             - '80:8080'
             - '443:443'
             - '50000:50000'
           volumes:
             - jenkins_data:/var/jenkins_home
             - /var/run/docker.sock:/var/run/docker.sock  
volumes:
        jenkins_data:



